# Generated by Django 2.0 on 2018-12-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='gender',
            field=models.TextField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
