# Generated by Django 2.0 on 2018-12-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
